version: '3.8'

services:
  scrapy-crawler:
    build: .
    container_name: persian-law-crawler
    volumes:
      # Mount data and logs directories to persist output
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Optional: if you need to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 1G